name = "karmel-api"

[env.dev]
TURSO_URL = "libsql://karmel-db-kndwin.turso.io"
TURSO_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOiIyMDI0LTAxLTIxVDE1OjI1OjM4LjA0NTA5ODY5OFoiLCJpZCI6IjA3MjZjNzA2LWI4NzEtMTFlZS1iMTg5LWE2MDMzNTNjNjBiMyJ9.BubgmJtStJvvGxqbS3OitLd10qZoItl727an-Hw8-R5_rR0HCiG3gX0xD2XP-S0wGvMkmOszx1Z--JLeZRztAQ"
GITHUB_CLIENT_ID="f7a7c5312960ff9e5177"
GITHUB_CLIENT_SECRET="5143e4e09b7759ec03835b98837f57a75c184f70"
WEB_PUSH_PUBLIC_KEY="BIWZcbfWo9sRdmUkeNP2WrdObJVRyqFd9G4XIMLYiriMaomkSSbsk3S8nbrfWHoHBAKhKp_XsG26hcDnGA48-VI"
WEB_PUSH_PRIVATE_KEY="MKESFhwNFDCb-pC2zR8mowkyi9l0cg0tpLzoiLNNRts"
